### ISSUE TITLE
Feature 1. Users can search fun dogs pictures, either by random, or by breed.

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#1]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive search tool for users to search fun dogs pictures, either by random, or by breed

## ✅ Task List

- [x] Create a header for the app, with app title, and picture search tag
- [x] Create the search section
- [x] Add search option buttons for users to choose from
- [x] Search option will be by breed or random
- [x] The default showing pic will be one
- [x] Using code in main.js to perform the AJAX task
  - [x] create a data model 
  - [x] Reset the search inputs.
- [x] Verify that searched pics are displayed properly on the screen
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
