### ISSUE TITLE
stretch feature 1- users can create their own pet logs and reminders

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create anchor elements in dashboard and header for log page and reminder showing 
- [ ] Update data model for new entry data
- [ ] Create form on the event log/ reminder page
- [ ] Create submit event to accurately obtain the right information 
- [ ] Create Dom generation function to display new entry and reminder
- [ ] Make sure that the Dom tree created displayed properly on the page
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
