### ISSUE TITLE
Stretch feature 2.  User can play a game guess puppy name games 

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can play a game with random puppy pic given and type in the breed name in a limited time

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

WireFrame

![Screen Shot 2021-09-24 at 12 24 00 PM](https://user-images.githubusercontent.com/88110300/134729577-517806cd-8ec6-4292-94a3-2d4cdb1b1b21.png)

![Screen Shot 2021-09-24 at 12 24 41 PM](https://user-images.githubusercontent.com/88110300/134729599-5afc97d3-59a5-4988-9ea4-7c93579a0ee5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] make a whole view page for game section in html
- [ ] add the view swap button on main page for the view swapping
- [ ] write function in main.js to perform the data acquiring from API for random puppy pic
- [ ] modified data model and applying method to obtain necessary breed info from API response
- [ ] write function in main.js to perform the timer function
- [ ] write function in main.js to perform the check answer feature
- [ ] add play again option 
- [ ] add record list
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
