### ISSUE TITLE
Users can view 1-3 pics in their search result.

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view 1-3 pics in their search result.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can either search dogs' pictures by breed or by random in 1-3 pics mode. 

## ✅ Task List

- [x] Create three buttons for pic number options
- [x] create event listener for each button to change color after the option is made
- [x] Using code in main.js to perform the updated AJAX task
  - [x] Update data model 
  - [x] Reset the search inputs.
- [x] Verify that searched pics are displayed properly on the screen
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
