### ISSUE TITLE
User can save any pictures they like

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save any pictures they like from the search result

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking save from the search result, user can save any picture they like to the puppy gallery

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

- [x] Update the Dom generator to add necessary attribute for the data obtained from API
- [x] Create function to save the required data to data model
- [x] Add function to the event element to perform the save process
- [x] Reset the search inputs.
- [x] Verify that saved data is stored properly in the data model.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
