### ISSUE TITLE
User can view a list of their saved pictures

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their saved pictures. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can organize their saved pictures by viewing and delecting
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

- [x] Add the new div in HTML for the gallery display
- [x] Adding the anchors elements in the header section
- [x] Write function for view changing to switch views between  pic search and pic gallery
- [x] Write code in main.js for a new render function to generate Dom for the gallery
- [x] Getting the right data from the data model to generate the Dom and add it on the screen
- [x] Verify that saved pic is displayed properly in the data model.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
-  [x] Fix all errors.
