### ISSUE TITLE
User can change the hero image with the saved picture and change background color. 

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/puppy-paradise#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change the hero image with the saved picture and change background color. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can choose any picture from gallery and set the hero image and background color with that picture. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

- [x] Add the new div in HTML for the app dashboard 
- [x] For the dashboard, build the hero block with hero image holder, the background holder and color button switchers
- [x] modify the render function, to add save background option to the pic in gallery
- [x] Write function for setting up the desired saved pic as the hero block image( screen will swap once the image is selected)
- [x] Write code in main.js for color buttons to be used to change the heroblock background color
- [x] Adding the exit tag on the hero block to exit the app
- [x] Verify that selected pic is displayed properly inside the hero block.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
-  [x] Fix all errors.
